server:
  port: 3000

spring:
  application:
    name: NOTIFICATION-SERVICE
  datasource:
    url: "jdbc:mysql://localhost:3306/notification_db"
    username: facebook
    password: facebook

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
