server:
  port: 4000

spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    url: "jdbc:mysql://localhost:3306/comment_db"
    username: facebook
    password: facebook

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
