server:
  port: 7000

spring:
  application:
    name: POST-SERVICE
  datasource:
    url: "jdbc:mysql://localhost:3306/post_db"
    username: facebook
    password: facebook

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


