server:
  port: 7000
  servlet:
    context-path: /post
spring:
  application:
    name: POST-SERVICE
  datasource:
    url: "jdbc:mysql://localhost:3306/post_db"
    username: facebook
    password: facebook

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
