server:
  port: 5000
  servlet:
    context-path: /like
spring:
  application:
    name: LIKE-SERVICE
  datasource:
    url: "jdbc:mysql://localhost:3306/like_db"
    username: facebook
    password: facebook

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka